name: Run Tests

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 20

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install Python dependencies with Poetry
      run: |
        python3 -m pip install poetry
        poetry install

    - name: Install Node dependencies
      run: |
        npm install --only=dev # Install development dependencies

    - name: Run Tests
      run: npm test
